source 'https://rubygems.org'
gem 'motion-testflight'
gem 'motion-cocoapods'
gem 'teacup'
gem 'sugarcube'#, '= 0.20.25'
gem 'rake'
gem 'rake-hooks'
gem 'motion-dtrace'
gem 'afmotion'
gem 'motion-calabash'
